require: rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

Metrics/MethodLength:
  Max: 20

RSpec/SubjectStub:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
RSpec/AnyInstance:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['puts','output']

Metrics/AbcSize:
  IgnoredMethods: ['send_money','destroy_card','send','',]

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
