require: rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

Metrics/MethodLength:
  Max: 20
  IgnoredMethods: ['create_card','destroy_card']

Layout/LineLength:
  IgnoredMethods: ['create_card','destroy_card']

RSpec/SubjectStub:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
